# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: node try
        run: |
          node -v
          node
          let a= ${{ secrets.TEST }}
          console.log(a)
          
          
 
        
