# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: bash script
        run: |
          #!/bin/bash
          for i in 1 2 3 4 5
          do
            echo "Welcome $i times"
          done
      - name: ls
        run: |
          node -v 
          npm -v 
          ls -l
          cd 
          ls -l
      - name: test location 
        run: |
          ls -l
      - name: bash
        env:
          key1: ${{secrets.TEST}}
        run: |
          echo $key1
          
          
          
 
        
